-- 이렇게도 풀 수 있군아

-- 짧은 CITY
SELECT CITY, LENGTH(CITY) 
FROM STATION 
ORDER BY LENGTH(CITY), CITY 
LIMIT 1;

-- 긴 CITY
SELECT CITY, LENGTH(CITY) 
FROM STATION 
ORDER BY LENGTH(CITY) DESC, CITY 
LIMIT 1;